In [2]:
# 1.split the String
n = "Hi ,i am  NaveenRAj!"
n.split()

['Hi', ',i', 'am', 'NaveenRAj!']

In [3]:
# 2.Use.format() to print the folllowing string.
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


In [4]:
# 3.In This nest Dictionary  Grap the Word "Hello"
n = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
n['k1'][3]['tricky'][3]['target'][3]

'hello'

In [5]:
import numpy as np

4.1 Create An Array of 10 Zeros?


In [6]:
arr_zeros = np.zeros(15)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 Create an Array of 10 Fives?

In [7]:
arr_fives = np.ones(10)*6
print(arr_fives)

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


5.Create an Array of All Even Integers From 20 to 25

In [8]:
even= list(np.arange(20,35,2))
print(even)

[20, 22, 24, 26, 28, 30, 32, 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
m = np.arange(11,20).reshape(3,3)
print(m)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


7. Concatinate a and b
a = np.array([1,2,3]),b =np.array([4,5,6])

In [10]:
n = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((n,b)))

[1 2 3 4 5 6]


Pandas 

8. Create a dataframe with 3 Rows and 2 columns

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(columns = ['C1', 'C2'], index = ['R1', 'R2', 'R3'])
df

C1   C2
R1  NaN  NaN
R2  NaN  NaN
R3  NaN  NaN

 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
dates = pd.date_range('1/11/2023','1/12/2023')
print(dates)

DatetimeIndex(['2023-01-11', '2023-01-12'], dtype='datetime64[ns]', freq='D')


10. Create 2D list to DataFrame

In [14]:
lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [16]:
df1 = pd.DataFrame(lists)
df1

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24