Basic Python

1. Split this string

In [3]:
a = "Hi i am akash"
a.split()

['Hi', 'i', 'am', 'akash']

2. Using .format() to print a string

In [5]:
place = "River Nile"
distance = 6650
print("The length of {} is {} kilometers.".format(place,distance))

The length of River Nile is 6650 kilometers.


3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['free','the','tenet',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [8]:
import numpy as np

4.1 Create an array of 10 zeros
4.2 Create an array of 10 fives

In [9]:
arr_zeros = np.zeros(10)
print(arr_zeros)
arr_fives = np.ones(10)*5
print(arr_fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [10]:
even_int = list(np.arange(20,35,2))
print(even_int)

[20, 22, 24, 26, 28, 30, 32, 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
w = np.arange(0,9).reshape(3,3)
print(w)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate a and b

In [12]:
a = np.array([1,7,11])
b = np.array([2,3,6])
print(np.concatenate((a,b)))

[ 1  7 11  2  3  6]


Pandas

8. Create a DataFrame with 3 rows and 2 columns

In [13]:
import pandas as pd
df = pd.DataFrame(columns = ['C1', 'C2'], index = ['R1', 'R2', 'R3'])
df

C1   C2
R1  NaN  NaN
R2  NaN  NaN
R3  NaN  NaN

9. Generate the series of dates from 1st Feb, 2024 to 15th Mar, 2023

In [14]:
dates = pd.date_range('2/1/2023','3/15/2023')
print(dates)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01', '2023-03-02', '2023-03-03', '2023-03-04',
               '2023-03-05', '2023-03-06', '2023-03-07', '2023-03-08',
               '2023-03-09', '2023-03-10', '2023-03-11', '2023-03-12',
               '2023-03-13', '2023-03-14', '2023-03-15'],
              dtype='datetime64[ns]', freq='D')


10. Convert 2D list to a DataFrame

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df1 = pd.DataFrame(lists)
df1

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24